# ---
# deployment:
#   tasks: 
#     - export DEPLOYPATH=/home/geonoteu/public_html/geo-app
    
#     # Создание директории и копирование
#     - /bin/mkdir -p $DEPLOYPATH
#     - /bin/cp -R * $DEPLOYPATH
    
#     # Переход в директорию
#     - cd $DEPLOYPATH
    
#     # Установка зависимостей
#     - npm install
    
#     # Сборка Next.js
#     - npm run build
    
#     # Перезапуск через cPanel Node.js App
#     - touch $DEPLOYPATH/tmp/restart.txt

---
deployment:

   tasks:

      - export DEPLOYPATH=/home/geonoteu/geonote.uz/geo-app
      - /bin/cp -R * $DEPLOYPATH